### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by Sci-Tek** [PaulHigin/PSThreadJob#33]
Memory consumtion if starting many jobs (25k), this memory is never released properly. But can sometimes be seen going down before increasing again.
Unsure if that is because I use get-job | where state -eq 'Completed' | remove-job after the jobs has been fired off.

ThrottleLimit seems to have no effect. Left process running for 15+ hours and eventually it just stops. First 10k jobs goes pretty fast but then memory starts becoming an issue and job completion gets slowed down more and more before eventually just stopping completley. (16gb memory).

Tested on
PSVersion 5.1.17763.316
PSEdition Desktop

PSVersion 6.2.0
PSEdition Core

-----

Easily reproducable with: 
```
1..25000 | % {
    $null = start-threadjob  -Name $_ -scriptblock { write-host $_ } -ThrottleLimit 50
}
```
You can monitor it by using this:

```
$starttime = get-date
$CompletedTotal = 0
$Remaining = 0
$jobs = Get-Job
$total = $jobs.count
Do {
    $jobs = Get-Job
    $Remaining = ($jobs | where { $_.state -notlike 'Running' -and $_.State -notlike 'Completed' -and $_state -notlike 'NotStarted' }).count
    $Running = ($jobs | where State -eq 'Running').count
    $Completed = ($jobs | where State -eq 'Completed').count
    $CompletedTotal += $Completed
    $percentage = (($CompletedTotal * (100/$total)) | Out-String).Substring(0,4)
    cls
    Write-host "
    Started: $starttime
    
    Total jobs: $total
    Running jobs: $running
    Completed jobs: $CompletedTotal ($percentage%)
    Last step: $Completed

    Remaining jobs: $Remaining

"
    $jobs | where state -eq 'Completed' | remove-job
    $CompletedTotal += $Completed
    start-sleep -Seconds 1
    
}
Until (($jobs | where State -eq 'Running').count -eq '0')

write-host "

Finished.

"

```

**Comment by PaulHigin** [comment]
I am not aware of any memory or handle leak, but I haven't done extensive testing.

You need to run 'Get-Job' to see the state of all 25K jobs created.  Job state will be at `NotStarted` until a running one completes.  But since your job script completes almost immediately, you will probably not see it since the job completes while the list is being displayed.  You can add a `sleep 1` to see the action better.  Or check the process thread count, which won't rise much above 50 (CLR creates its own threads).

25K job objects is a lot of jobs and will definitely use up a bunch of memory.  Much of the memory will stick around while the job object exists and until you remove the jobs via `Get-Job | Remove-Job`.

The runspaces used to execute the script block gets cleaned up and you should never see more than ~50 while the jobs are running:

```powershell
PS> Get-Runspace
```

But you will likely see the memory pressure persist until you force the CLR to garbage collect.  You can do this with:
```powershell
PS> [System.GC]::Collect()
```

**Comment by Sci-Tek** [comment]
Thanks for the advice, the [System.GC]::Collect() actually do seem to have an impact in cleaning up memory. .However it do not cleanup all the times when invoked (and jobs are removed). But it seems to be consistent in cleaning up memory after all jobs are removed.

```

    $jobs | where state -eq 'Completed' | remove-job
    $proc = Get-Process -id $pid 
 if ($proc.WorkingSet64 -gt 5000000000){
     $GCCdate = get-date
     $GCCdifference = $GCCdate-$GCClastrun

     if($GCCdifference.totalseconds -gt '180'){
     Start-Process powershell.exe -ArgumentList "-command [System.GC]::Collect()"
     $GCClastrun = get-date
     }
    }
```
